### ISSUE TITLE
Document Please, Thanks

### ISSUE THREAD

**Issue by jsg10** [amanbolat/gofmcon#2]
I can't link to DB, always return:

~~~

# sandbox/models
../models/models.go:13:17: fmrecord.ToMap undefined (type *gofmcon.Record has no field or method ToMap)
../models/models.go:14:19: fmrecord.ToMap undefined (type *gofmcon.Record has no field or method ToMap)

~~~

**Comment by amanbolat** [comment]
@regnarts Yes, API is changing, and not well tested. I already have some fixes and will document them soon.

**Comment by jsg10** [comment]
Cool. Looking forward to updating the documentation. Thank you.

**Comment by amanbolat** [comment]
@regnarts I updated this repo. Please look for new documentation in README.me

There is no more `ToMap` method.

To get value of field you should use `Field` method.

**Comment by jsg10** [comment]
Cool, thank you so much. I will try it tonight.

**Comment by jsg10** [comment]
The connection is successful and the data is got. It's great.

Well Done ! ! !

**Comment by amanbolat** [comment]
@regnarts I'm glad to hear good news.
