### ISSUE TITLE
How to query one line？need a sample

### ISSUE THREAD

**Issue by jsg10** [amanbolat/gofmcon#3]
It's me again.

I don't know how to use "Get single record" in function. 

Always show errors:  `assignment mismatch: 2 variables but 1 values` in line q.WithFields

This is the code :

```
// get single result
func (ps *rpdStore) GetOneRep(conn *fm.FMConnector) (*ReportDocument, error) {

	var rpd ReportDocument
	q := fm.NewFMQuery(ps.dbName, "reportDocument", fm.Find)
	rpd, err := q.WithFields( // show error: assignment mismatch: 2 variables but 1 values
		fm.FMQueryField{Name: "id", Value: "d0000000001", Op: fm.Equal},
	).WithMaxRecords(1)

	return &rpd, nil // result
}
```

**Comment by amanbolat** [comment]
It's not a problem of library. Theres is mistake in your code.

This should work:
```
// get single result
func (ps *rpdStore) GetOneRep(conn *fm.FMConnector) (*ReportDocument, error) {

	var rpd ReportDocument
	q := fm.NewFMQuery(ps.dbName, "reportDocument", fm.Find)
	q.WithFields( // show error: assignment mismatch: 2 variables but 1 values
		fm.FMQueryField{Name: "id", Value: "d0000000001", Op: fm.Equal},
	).WithMaxRecords(1)

	return &rpd, nil // result
}
```
q.WithFields() method returns same FMQuery and it's only one variable. It does not return error.

After creating FMQuery you just use FMConnector to request records:

```
func (ps *rpdStore) GetOneRep(conn *fm.FMConnector) (*ReportDocument, error) {

	var rpd ReportDocument
	q := fm.NewFMQuery(ps.dbName, "reportDocument", fm.Find)
	q.WithFields( // show error: assignment mismatch: 2 variables but 1 values
		fm.FMQueryField{Name: "id", Value: "d0000000001", Op: fm.Equal},
	).WithMaxRecords(1)

       fmSet, err := conn.Query(q)
       rpd = &ReportDocument{}
       rpd.Populate(fmset.Resultset.Records[0:])                                   
	
	return &rpd, nil // result
}
```

Your ReportDocument struct should have some method like Post struct in README file to Unmarshal FMRecord. 

I think you should read some FileMaker XML WebPublishing documentation to understand how my library wokrs.

**Comment by jsg10** [comment]
> It's not a problem of library. Theres is mistake in your code.
> 
> This should work:
> 
> ```
> // get single result
> func (ps *rpdStore) GetOneRep(conn *fm.FMConnector) (*ReportDocument, error) {
> 
> 	var rpd ReportDocument
> 	q := fm.NewFMQuery(ps.dbName, "reportDocument", fm.Find)
> 	q.WithFields( // show error: assignment mismatch: 2 variables but 1 values
> 		fm.FMQueryField{Name: "id", Value: "d0000000001", Op: fm.Equal},
> 	).WithMaxRecords(1)
> 
> 	return &rpd, nil // result
> }
> ```
> q.WithFields() method returns same FMQuery and it's only one variable. It does not return error.
> 
> After creating FMQuery you just use FMConnector to request records:
> 
> ```
> func (ps *rpdStore) GetOneRep(conn *fm.FMConnector) (*ReportDocument, error) {
> 
> 	var rpd ReportDocument
> 	q := fm.NewFMQuery(ps.dbName, "reportDocument", fm.Find)
> 	q.WithFields( // show error: assignment mismatch: 2 variables but 1 values
> 		fm.FMQueryField{Name: "id", Value: "d0000000001", Op: fm.Equal},
> 	).WithMaxRecords(1)
> 
>        fmSet, err := conn.Query(q)
>        rpd = &ReportDocument{}
>        rpd.Populate(fmset.Resultset.Records[0:])                                   
> 	
> 	return &rpd, nil // result
> }
> ```
> Your ReportDocument struct should have some method like Post struct in README file to Unmarshal FMRecord.
> 
> I think you should read some FileMaker XML WebPublishing documentation to understand how my library wokrs.

Yes, It's really a mistake of my code, I have fix it with your help.

Thank you soooo much. And I will read FileMaker XML WebPublishing documentation as soon as possible.
