### ISSUE TITLE
How to deal with HTTPS or 18.0.4

### ISSUE THREAD

**Issue by jsg10** [amanbolat/gofmcon#4]
After I upgrade Filemaker Server to 18.0.4 . I use a custom SSL in the Server. Then my app give an error:

`gofmcon.Query: error unmarshal xml: XML syntax error on line 5: invalid UTF-8`

Is that because of the upgrade or use SSL?

**Comment by amanbolat** [comment]
Please, try to use some API debugger to make Filemaker API calls directly without using this library, then look at the xml response. If it's ok then try to use go/xml library to unmarshal it. I think problem is in the data that was received from you FileMaker server.

**Comment by jsg10** [comment]
Thanks, I can't find where is the problem, so I try another way. Thanks a lot.

**Comment by jsg10** [comment]
> Please, try to use some API debugger to make Filemaker API calls directly without using this library, then look at the xml response. If it's ok then try to use go/xml library to unmarshal it. I think problem is in the data that was received from you FileMaker server.

I found the problem. That's because after Upgraded the server I forgot to open fmxml by using the CLI `fmsadmin set cwpconfig enablexml=true`. I 'm so sorry that there is nothing wrong with the lib, it is all my fault.

**Comment by amanbolat** [comment]
Nice. Open new issue if will have any other questions.
